### ISSUE TITLE
Update Jekyll version to 4.0.0

### ISSUE THREAD

**Issue by Retro64XYZ** [julianolf/jekyll-theme-8bit#10]
```
$ bundle update
```

```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-theme-8bit was resolved to 0.3.0, which depends on
      jekyll (~> 3.8.5)
```

**Comment by julianolf** [comment]
@Retro64XYZ 

First of all I would like to apologize for taking so long to reply. I didn't saw the notification back in the day when you opened this issue and I also haven't visited this project in a while.

The version of Jekyll used by this project is really outdated, as far as I can see in Jekyll's homepage the current version is 4.1.1.

My only concern is about GitHub Pages support, but if the newer version works I think the update should be done.

I'll try to check this out.

But if you have already tested and want to contribute feel free to open a pull request. 🙂 

Cheers.

**Comment by julianolf** [comment]
@Retro64XYZ I just realized that [dependabot](https://dependabot.com/) has already updated Jekyll's version, so all I had to do was publish a new gem version.
