### ISSUE TITLE
Forking to github page doesn't create

### ISSUE THREAD

**Issue by ctvw** [julianolf/jekyll-theme-8bit#24]
Forking this repo to a github page doesn't seem to bundle the theme.

**Comment by julianolf** [comment]
Hi @ctvw.

Could you give some details on the process you did? Have you followed the GitHub Pages guidelines?

This repository defines a theme for Jekyll as a Ruby Gem, so I would normally recommend to enable GitHub Pages in your repository and set the theme to `Jekyll-theme-8bit`.

But forking and enabling GitHub Pages in the repository settings should also works.

**Comment by julianolf** [comment]
I'm not sure if this could be the issue you were facing but I merged a new PR here and the build failed.

Looking at the output error it seemed the theme had not been found. I went to the [documentation](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll) and saw that custom themes now requires a specific configuration attribute, `remote_theme`, pointing to a GitHub repository with the theme source code.

After changing that the build succeeded.

**Comment by julianolf** [comment]
Hi @ctvw.

It's been a year since you opened this issue and I'm not sure if you still trying to use the theme without success.

Because you haven't reached back here I'm closing this issue but feel free to open it again if you still need help.
