### ISSUE TITLE
Theme compatibility with later versions of Jekyll

### ISSUE THREAD

**Issue by cjwilburn** [julianolf/jekyll-theme-8bit#27]
Hello!

I was attempting to apply this theme locally. I'm using Jelkyll version 4.3.2 and it appears that this theme is only compatible with versions of Jekyll  <= 4.2.x. If there's a straghtforward way for me assist in making it compatible with later versions of Jekyll, I'm happy to help.

Thanks in advance!

EDITED TO ADD: It looks like there are some dependabot dependency PRs to the `Gemspec` that if merged could do the trick. Happy to help in whatever way possible with this, since I like this theme so much.

**Comment by julianolf** [comment]
Hi @cjwilburn.

First of all I'm truly sorry for taking so long to reach you back, I've been overwhelmed with GitHub notifications from my daily job and I might have accidentally marked your message as read.

I'm glad that you enjoy the theme.

About the support to Jekyll 4.3.2, you are right, the pull request #26 allows the theme to be used with this vesion.

After some test it seems everything is alright so I'm releasing a new version of the theme. If you update your version and face any issues please let me known.

And if you want to test changes to the theme locally here is what I usually do (after cloning this repository):

* Create a new branch so I can change things freely, merge when I'm finished or discard them if I don't like the result or something breaks.
  * In this case the changes were already made by Dependabot so I just needed to checkout the branch.
```sh
git checkout dependabot/bundler/jekyll-gte-3.8.5-and-lt-4.4.0
```
* Then install or update the local dependencies using Bundler.
```sh
bundle install
```
* Lastly run Jekyll's local server.
```sh
bundle exec jekyll serve
```
After these steps I can check the changes on a web browser at `http://127.0.0.1:4000`.

That's it :)

Best regards.
